version: '2'
services:
  ssh:
    image: 'dockersecplayground/alpine_ssh_password:v1.0'
    stdin_open: true
    tty: true
    ports:
      - '22000:22'
    networks:
      internal_network:
        ipv4_address: 192.168.1.5
    cap_add:
      - NET_ADMIN
  router:
    image: 'dockersecplayground/alpine_router:v1.0'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.1.2
      external_network:
        ipv4_address: 192.168.2.2
    cap_add:
      - ALL
  website:
    image: 'dockersecplayground/linode_lamp:v1.0'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.1.3
    volumes:
      - './website:/var/www/example.com/public_html'
    cap_add:
      - NET_ADMIN
networks:
  internal_network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
  external_network:
    ipam:
      config:
        - subnet: 192.168.2.1/24
